### ISSUE TITLE
Styling & formatting for GBE

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno-by-example#158]
## Description

Here are some minor styling & formatting improvements that could be implemented for GBE.

1. Home page organization: I'm not a designer by any means, but I think it would be awesome to have a large banner, and below it have the sections listed horizontally. The sections can be dropdowns, or cards with a short section description that people can open up. I can ask the design team for some ideas/figma files.
2. Weird gap between file name & line 1 in code
<img width="1026" alt="Screenshot 2024-04-17 at 15 28 06" src="https://github.com/gnolang/gno-by-example/assets/33522493/c7960f22-0db5-44c7-9879-b9f0d9fd7cc8">
3. Code options could be automatically expanded in the code viewer, since there is a lot of unused space
<img width="1024" alt="Screenshot 2024-04-17 at 15 29 21" src="https://github.com/gnolang/gno-by-example/assets/33522493/d436cd9e-6571-4b6d-a014-c8d5c2144d0c">  

4. Possibly add a  "Open in Playground" button  
5. While inside a specific tutorial, have a sidebar with the other tutorials in the section, for easier navigation  
6. Interlinking with the Official docs & Playground  

@zivkovicmilos, since you're busy, I will see with @alexiscolin if he has a bit of bandwidth to work on the frontend side of things.

**Comment by alexiscolin** [comment]
Other Playground issues may be fixed with the new embedded playground that will come soon.
https://github.com/gnostudio/studio/pull/970
