### ISSUE TITLE
Titles not escaped properly break generation

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno-by-example#166]
## Description

As title says, some titles will break the tutorial generation script:
- This is a \`title\`
- This is a title()
- Characters disallowed in code, such as `&`

I propose we introduce a new field in the metadata - a tutorial ID, or slug, which will be unique to the section the tutorial is in, while keeping the title as a normal, quoted string to be displayed on the website.

**Comment by alexiscolin** [comment]
@leohhhn You must escape this kind of symbols with `\`
